name: VTL grammar tests

on:
  workflow_dispatch:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened]

jobs:
  vtl-grammar-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Run tests with Maven
        working-directory: v2.2
        run: mvn --batch-mode --fail-at-end clean verify
