name: Recheck PRs when Master is updated

on:
  push:
    branches: [master]

jobs:
  recheck-open-prs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      pull-requests: read
    steps:
      - name: Check that each PR is fast forward
        uses: actions/github-script@v7
        with:
          script: |
            const prs = await github.paginate(
              github.rest.pulls.list,
              {
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'open',
                base: 'master'
              }
            );

            for (const pr of prs) {
              await github.rest.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: 'is-fast-forward.yaml', // name of the file in .github/workflows/
                ref: pr.head.ref,
                inputs: {
                  pr_ref: pr.head.ref
                }
              });
            }
